# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Propel
description: > # this means to ignore newlines until "baseurl:"
  Propel is a library that simplifies adding push notifications to a web
  app.
baseurl: "/docs-playground" # the subpath of your site, e.g. /blog
url: "https://github.com/googlechrome/propel" # the base hostname & protocol for your site
github_link: "https://github.com/googlechrome/propel"
# Build settings
markdown: kramdown
